[INFO   ] Logger: Record log in /storage/emulated/0/Python/Testes/.kivy/logs/kivy_22-02-28_16.txt
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.9.7 (default, Oct  9 2021, 08:02:40) 
[GCC 11.1.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/python3"
[INFO   ] Factory: 186 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/__init__.py", line 5, in <module>
[WARNING] stderr:     from Views.Main import MainView
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/Views/Main.py", line 5, in <module>
[WARNING] stderr:     from Controllers import connection_controller
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/Controllers/connection_controller.py", line 1, in <module>
[WARNING] stderr:     from Controllers import views_controller
[WARNING] stderr: ImportError: cannot import name 'views_controller' from 'Controllers' (unknown location)
