[INFO   ] Logger: Record log in /storage/emulated/0/Python/Testes/.kivy/logs/kivy_22-02-27_21.txt
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.9.7 (default, Oct  9 2021, 08:02:40) 
[GCC 11.1.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/python3"
[INFO   ] Factory: 186 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.1 v1.r7p0-02rel0.4ea33e6671ff828e33c99c982634cd65'>
[INFO   ] GL: OpenGL vendor <b'ARM'>
[INFO   ] GL: OpenGL renderer <b'Mali-T720'>
[INFO   ] GL: OpenGL parsed version: 3, 1
[INFO   ] GL: Texture max size <8192>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] GL: NPOT texture support is available
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/__init__.py", line 21, in <module>
[WARNING] stderr:     Application().run()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/app.py", line 949, in run
[WARNING] stderr:     self._run_prepare()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/app.py", line 919, in _run_prepare
[WARNING] stderr:     root = self.build()
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/__init__.py", line 19, in build
[WARNING] stderr:     return Manager()
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/__init__.py", line 11, in __init__
[WARNING] stderr:     self.setup()
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/__init__.py", line 15, in setup
[WARNING] stderr:     self.add_widget(LoginView(name="Login", screen_manager=self))
[WARNING] stderr: TypeError: __init__() got an unexpected keyword argument 'screen_manager'
[WARNING] stderr: Exception in thread Thread-1:
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/threading.py", line 973, in _bootstrap_inner
[WARNING] stderr:     self.run()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/threading.py", line 910, in run
[WARNING] stderr:     self._target(*self._args, **self._kwargs)
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/Views/Main.py", line 31, in connection_state
[WARNING] stderr:     views_controller.login()
[WARNING] stderr: NameError: name 'views_controller' is not defined
